### ISSUE TITLE
Regression in Boost 1.81 for initializer lists

### ISSUE THREAD

**Issue by saki-dev** [boostorg/json#823]
Environment:
- Visual Studio 2022 c17.4.3
- Example code compiles with Boost 1.80, but not with 1.81

Example code similar to examples in documentation with added vector:
```
#include <boost/json.hpp>
#include <iostream>
#include <string>
#include <vector>

struct customer
{
    int id;
    std::string name;
    bool current;
    std::vector<int> dimensions;
};

void tag_invoke(boost::json::value_from_tag, boost::json::value& jv, customer const& c)
{
    jv = 
    {
        { "id" , c.id },
        { "name", c.name },
        { "current", c.current },
        { "dimensions", c.dimensions }
    };
}

int main()
{
    customer cust{ 1, "bar", true, {20, 20, 20} };
    auto jsonValue = boost::json::value_from(cust);
    std::cout << boost::json::serialize(jsonValue);
}
```

Error log:
```
1>CodeTests.cpp
1>_redacted_path_\boost\boost\json\impl\value_ref.hpp(35,17): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'boost::json::value'
1>_redacted_path_\boost\boost\json\impl\value_ref.hpp(35,17): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>_redacted_path_\boost\boost\json\value_ref.hpp(204,1): message : see reference to function template instantiation 'boost::json::value boost::json::value_ref::from_const<std::vector<int,std::allocator<int>>>(const void *,boost::json::storage_ptr)' being compiled
1>_redacted_path_\CodeTests\CodeTests.cpp(24,5): message : see reference to function template instantiation 'boost::json::value_ref::value_ref<std::vector<int,std::allocator<int>>>(const T &,void *) noexcept' being compiled
1>        with
1>        [
1>            T=std::vector<int,std::allocator<int>>
1>        ]
```

**Comment by grisumbras** [comment]
The problem is with `{ "dimensions", c.dimensions }`. This was never supposed to work. Please, replace with `{ "dimensions", value_from(c.dimensions) }`.

**Comment by saki-dev** [comment]
Yeah, now it works. Sorry for bothering you. I supposed it was a regression as it was working with older version of Boost.

**Comment by grisumbras** [comment]
Sure, I can undestand your confusion.
