### ISSUE TITLE
1.79 fails to compile with GCC 12.1.0

### ISSUE THREAD

**Issue by Garzet** [boostorg/json#725]
### Version of Boost

**1.79**

### Steps necessary to reproduce the problem

```cpp
#include <boost/json.hpp>
int main() { boost::json::object obj; }
```
Compile with:
`g++ -std=c++17 main.cpp -l:libboost_json.a`

### All relevant compiler information

GCC version **12.1.0**
Compiler output:
```
In file included from /usr/include/boost/json/string_view.hpp:14,
                 from /usr/include/boost/json/kind.hpp:14,
                 from /usr/include/boost/json/array.hpp:14,
                 from /usr/include/boost/json.hpp:15,
                 from test.cpp:1:
/usr/include/boost/core/detail/string_view.hpp:1228:13: error: ‘basic_common_reference’ is not a class template
 1228 | struct std::basic_common_reference<
      |             ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/core/detail/string_view.hpp:1232:1: error: qualified name does not name a class before ‘{’ token
 1232 | {
      | ^
/usr/include/boost/core/detail/string_view.hpp:1237:13: error: ‘basic_common_reference’ is not a class template
 1237 | struct std::basic_common_reference<
      |             ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/core/detail/string_view.hpp:1241:1: error: qualified name does not name a class before ‘{’ token
 1241 | {
      | ^
In file included from /usr/include/boost/json/string.hpp:19,
                 from /usr/include/boost/json/value.hpp:20,
                 from /usr/include/boost/json/array.hpp:1756:
/usr/include/boost/json/value.hpp: In member function ‘typename std::enable_if<(std::is_arithmetic<_Tp>::value && (! std::is_same<Bool, bool>::value)), T>::type boost::json::value::to_number(boost::json::error_code&) const’:
/usr/include/boost/json/value.hpp:2372:9: error: cannot convert ‘boost::json::error’ to ‘int’
 2372 |         BOOST_JSON_ASSIGN_ERROR_CODE(ec, e, &loc);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         boost::json::error
In file included from /usr/include/boost/json/system_error.hpp:14,
                 from /usr/include/boost/json/error.hpp:14,
                 from /usr/include/boost/json/detail/except.hpp:13:
/usr/local/include/boost/system/error_code.hpp:601:45: note:   initializing argument 1 of ‘constexpr void boost::system::error_code::assign(int, const boost::system::error_category&)’
  601 |     BOOST_SYSTEM_CONSTEXPR void assign( int val, const error_category & cat ) BOOST_NOEXCEPT
      |
```

Not sure, but it seams like C++ standard is not being detected correctly as `std::basic_common_reference` is a C++20 thing. I downgraded boost to 1.78 and it compiles fine.

**Comment by grisumbras** [comment]
@pdimov can you look at this?

**Comment by pdimov** [comment]
Seems to work on CE: https://godbolt.org/z/bY79PM363

The use of `std::basic_common_reference` is guarded by `#if !defined(BOOST_NO_CXX20_HDR_CONCEPTS)`: https://github.com/boostorg/core/blob/b6c31904685e08fb7d9524f8cae961c0bd04cf31/include/boost/core/detail/string_view.hpp#L1234

There might be something wrong with the installation, such as Boost.Config not being the right version. And, looking at the second error, Boost.System doesn't seem to be the right version either.

**Comment by Garzet** [comment]
Thanks, it must be issue with my installation then.
Sorry for time wasted.
